# All additional class and sty files are stored in ~/.config/tex/, load them
$ENV{'TEXINPUTS'}='~/.config/tex/:' . $ENV{'TEXINPUTS'};
# Move build output to its own folder to avoid clutter in the main directory
$out_dir = '_build';
# Use pdftex
$pdf_mode = 1;
