config:
  dotpath: ~/.dotfiles
  backup: false
  banner: false
  link_by_default: true
  import_actions:
    - vim/actions.yaml

dynvariables:
  os: uname

dotfiles:

  f_tmuxconf:
    src: tmux/tmux
    dst: ~/.tmux.conf
    link: true

  f_ssh_config:
    src: ssh/config
    dst: ~/.ssh/config

  f_gitconfig:
    src: git/config
    dst: ~/.gitconfig

  f_zshrc:
    src: zsh/zshrc
    dst: ~/.zshrc

  f_bashrc:
    src: bash/bashrc
    dst: ~/.bashrc
  f_bash_profile:
    src: bash/bashrc
    dst: ~/.bash_profile

  f_vimrc:
    src: vim/vimrc
    dst: ~/.vimrc
    link: true
    actions:
      - vim_make_dirs
      - vim_download_plug
      - vim_install_plugins
  f_gvimrc:
    src: vim/gvimrc
    dst: ~/.gvimrc
    link: true
  d_vim_lang:
    src: vim/lang
    dst: ~/.vim/ftplugin
    link: true
  d_vim_syntax:
    src: vim/syntax
    dst: ~/.vim/after/syntax
    link: true

profiles:

  darwin:
    dotfiles:
      - ALL
  nimrodel:
    include:
      - darwin
  soft5.vub.ac.be:
    include:
      - nimrodel

  linux:
    dotfiles:
      - f_tmuxconf
      - f_ssh_config
      - f_gitconfig
      - f_zshrc
      - f_bashrc
      - f_bash_profile
      - f_vimrc
      - d_vim_lang
      - d_vim_syntax
  mirkwood:
    include:
      - linux
  gondolin:
    include:
      - linux
  serenity:
    include:
      - linux
  isabelle:
    include:
      - linux
