config:
  dotpath: ~/.dotfiles
  backup: false
  banner: false
  link_dotfile_default: link

dynvariables:
  os: uname

actions:
  vim_make_dirs: mkdir -p ~/.tmp/vim/backup ~/.tmp/vim/swap ~/.tmp/vim/undo
  vim_download_plug: curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  vim_install_plugins: vim +PlugInstall +qall now

  emacs_install_config: emacs -nw -Q ~/.emacs.d/configuration.org --eval '(org-babel-tangle)' --eval '(kill-emacs)'

dotfiles:

  tmuxconf:
    src: tmux/tmux
    dst: ~/.tmux.conf
    link: link

  ssh_config:
    src: _accounts/ssh/config
    dst: ~/.ssh/config

  gitconfig:
    src: git/config
    dst: ~/.gitconfig

  zsh:
    src: zsh/zshrc
    dst: ~/.zshrc

  bashrc:
    src: bash/bashrc
    dst: ~/.bashrc
  bash_profile:
    src: bash/bashrc
    dst: ~/.bash_profile

  neomutt:
    src: neomutt
    dst: ~/.config/neomutt
    link: link_children
  neomutt_accounts:
    src: _accounts/neomutt
    dst: ~/.config/neomutt
    link: link_children

  offlineimap:
    src: _accounts/offlineimap/config.conf
    dst: ~/.config/offlineimap/config

  msmtp:
    src: _accounts/msmtp/config
    dst: ~/.config/msmtp/config

  netrc:
    src: _accounts/netrc
    dst: ~/.netrc

  emacs:
    src: emacs
    dst: ~/.emacs.d/
    link: link_children
    actions:
      - emacs_install_config

  vim:
    src: vim
    dst: ~/.vim/
    link: link_children
    actions:
      - vim_make_dirs
      - vim_download_plug
      - vim_install_plugins

  latexmkrc:
    src: tex/latexmkrc
    dst: ~/.latexmkrc
  tex:
    src: tex/packages/
    dst: ~/.tex

profiles:

  darwin:
    dotfiles:
      - ALL
  nimrodel:
    include:
      - darwin
  soft5.vub.ac.be:
    include:
      - nimrodel

  linux:
    dotfiles:
      - tmuxconf
      - ssh_config
      - gitconfig
      - zsh
      - bashrc
      - bash_profile
      - vim
  mirkwood:
    include:
      - linux
  gondolin:
    include:
      - linux
  serenity:
    include:
      - linux
  isabelle:
    include:
      - linux
