config:
  backup: false
  banner: false
  dotpath: ~/.dotfiles
  link_dotfile_default: link
  func_file: [template_functions.py]

variables:
  trusted: false
  mail: false

actions:
  vim_make_dirs: mkdir -p ~/.vim/backup ~/.vim/swap ~/.vim/undo ~/.vim/sessions
  mbsync_create_maildirs: ~/.dotfiles/_accounts/mbsync/create_dirs.sh
  neomutt_create_cache_dir: mkdir -p ~/.tmp/neomutt/cache/header/

dotfiles:
  tmuxconf:
    src: tmux/tmux
    dst: ~/.tmux.conf

  ssh_config:
    src: ssh/config
    dst: ~/.ssh/config

  gitconfig:
    src: git/config
    dst: ~/.gitconfig

  zshrc:
    src: zsh/zshrc
    dst: ~/.zshrc

  bashrc:
    src: bash/bashrc
    dst: ~/.bashrc
  bash_profile:
    src: bash/bashrc
    dst: ~/.bash_profile

  neomutt:
    src: neomutt
    dst: ~/.config/neomutt
    link: link_children
    actions:
      - neomutt_create_cache_dir
  neomutt_accounts:
    src: _accounts/neomutt
    dst: ~/.config/neomutt
    link: link_children

  mailcap:
    src: mailcap/mailcap
    dst: ~/.mailcap

  mbsync:
    src: _accounts/mbsync/mbsyncrc
    dst: ~/.mbsyncrc
    actions:
      - mbsync_create_maildirs

  msmtp:
    src: _accounts/msmtp/config
    dst: ~/.config/msmtp/config

  netrc:
    src: _accounts/netrc
    dst: ~/.netrc

  emacs:
    src: emacs
    dst: ~/.emacs.d/
    link: link_children

  vim:
    src: vim
    dst: ~/.vim/
    link: link_children
    actions:
      - vim_make_dirs

  latexmkrc:
    src: tex/latexmkrc
    dst: ~/.latexmkrc
  tex:
    src: tex/packages/
    dst: ~/.tex

profiles:
  # Set up several groups which can be used at will.
  base:
    dotfiles:
      - vim
      - zshrc
      - bashrc
      - bash_profile
      - gitconfig
      - tmuxconf
  work:
    dotfiles:
      - emacs
      - latexmkrc
      - tex
  mail:
    dotfiles:
      - neomutt
      - neomutt_accounts
      - mailcap
      - mbsync
      - msmtp
      - netrc
    variables:
      mail: true
  trusted:
    dotfiles:
      - ssh_config
    variables:
      trusted: true

  # Generic profiles
  root:
    include:
      - base

  # Hostname-based profiles
  greenwood:
    include:
      - base
  gondolin:
    include:
      - base
  firefly:
    include:
      - base
  isabelle:
    include:
      - base
  nimrodel:
    include:
      - base
      - trusted
  silverlode:
    include:
      - base
      - mail
      - work
      - trusted
  sirion:
    include:
      - base
      - trusted
