config:
  dotpath: ./
  backup: false
  banner: false
  link_dotfile_default: link
  import_variables:
  - local.yaml:optional
  - uservariables.yaml:optional

dotfiles:
  bashrc:
    src: bash/bashrc
    dst: ~/.bashrc
  bash_profile:
    src: bash/bashrc
    dst: ~/.bash_profile
  gitconfig:
    src: git/config
    dst: ~/.config/git/config
  gitignore:
    src: git/ignore
    dst: ~/.config/git/ignore
  tmuxconf:
    src: tmux/tmux
    dst: ~/.config/tmux/tmux.conf
  vim:
    src: vim
    dst: ~/.vim/
    link: link_children
    actions:
    - vim_make_dirs

  zshrc:
    src: zsh/zshrc
    dst: ~/.zshrc
  mailcap:
    src: mailcap/mailcap
    dst: ~/.mailcap
  mbsync:
    src: mbsync/mbsyncrc
    dst: ~/.mbsyncrc
    actions:
    - mbsync_create_maildirs

  msmtp:
    src: msmtp/config
    dst: ~/.config/msmtp/config
  neomutt:
    src: neomutt
    dst: ~/.config/neomutt
    link: link_children
    actions:
    - neomutt_create_cache_dir

  emacs:
    src: emacs
    dst: ~/.config/emacs/
    link: link_children
  latexmkrc:
    src: tex/latexmkrc
    dst: ~/.config/latexmk/latexmkrc
  ssh_config:
    src: ssh/config
    dst: ~/.ssh/config
  tex:
    src: tex/packages/
    dst: ~/.config/tex
  dunst:
    src: dunst/dunstrc
    dst: ~/.config/dunst/dunstrc
  foot:
    src: foot/foot.ini
    dst: ~/.config/foot/foot.ini
  shikane:
    src: shikane/config.toml
    dst: ~/.config/shikane/config.toml
  rofi:
    src: rofi/config.rasi
    dst: ~/.config/rofi/config.rasi
  swappy:
    src: swappy/config
    dst: ~/.config/swappy/config
  sway:
    src: sway
    dst: ~/.config/sway
    link: link_children
  swayidle:
    src: swayidle
    dst: ~/.config/swayidle
    link: link_children
    actions:
    - swayidle_link_default
  swaylock:
    src: swaylock/config
    dst: ~/.config/swaylock/config
  waybar:
    src: waybar
    dst: ~/.config/waybar
    link: link_children
  wlogout:
    src: wlogout
    dst: ~/.config/wlogout
    link: link_children
  mpd:
    src: mpd/mpd.conf
    dst: ~/.config/mpd/mpd.conf
  ncmpcpp:
    src: ncmpcpp
    dst: ~/.config/ncmpcpp
    link: link_children
  systemd:
    src: systemd
    dst: ~/.config/systemd/user
    link: link_children
actions:
  vim_make_dirs: mkdir -p ~/.vim/backup ~/.vim/swap ~/.vim/undo ~/.vim/sessions
  mbsync_create_maildirs: '{%@@ for account in mbsync @@%} mkdir -p ~/.local/mail/{{@@
    account @@}} ;{%@@ endfor @@%} '
  neomutt_create_cache_dir: mkdir -p ~/.cache/neomutt/header/
  swayidle_link_default: ln -s ~/.config/swayidle/laptop ~/.config/swayidle/config
uservariables:
  email: email
  name: Full name
variables:
  editor: vim
  visual: vim
  signkey: false
  userctl: false
  path: false
  unlock: false
  mail: false
  ssh: false
profiles:
  core:
    dotfiles:
    - bashrc
    - bash_profile
    - gitconfig
    - gitignore
    - tmuxconf
    - vim
    - zshrc

  # Set for mail-related utilities
  mail:
    dotfiles:
    - neomutt
    - mailcap
    - mbsync
    - msmtp

  # Sway-based desktop
  sway_desktop:
    dotfiles:
    - dunst
    - foot
    - shikane
    - rofi
    - swappy
    - sway
    - swayidle
    - swaylock
    - systemd
    - waybar
    - wlogout

  mpd:
    dotfiles:
    - mpd
    - ncmpcpp

  # Hostname-based profiles
  silverlode:
    include:
    - core
    - mail
    dotfiles:
    - emacs
    - latexmkrc
    - ssh_config
    - tex

  sirion:
    include:
    - core
    - mail
    - sway_desktop
    - mpd
    dotfiles:
    - emacs
    - ssh_config
    - latexmkrc
