config:
  dotpath: ~/.dotfiles
  backup: false
  banner: false

dynvariables:
  os: uname

actions:
  vim_make_dirs: mkdir -p ~/.tmp/vim/backup ~/.tmp/vim/swap ~/.tmp/vim/undo
  vim_download_plug: curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  vim_install_plugins: vim +PlugInstall +qall now

dotfiles:

  tmuxconf:
    src: tmux/tmux
    dst: ~/.tmux.conf
    link: link

  ssh_config:
    src: ssh/config
    dst: ~/.ssh/config

  gitconfig:
    src: git/config
    dst: ~/.gitconfig

  zsh:
    src: zsh/zshrc
    dst: ~/.zshrc

  bashrc:
    src: bash/bashrc
    dst: ~/.bashrc
  bash_profile:
    src: bash/bashrc
    dst: ~/.bash_profile

  aerc_conf:
    src: aerc/aerc.conf
    dst: ~/.config/aerc/aerc.conf
  aerc_binds:
    src: aerc/binds.conf
    dst: ~/.config/aerc/binds.conf

  vim:
    src: vim
    dst: ~/.vim/
    link: link_children
    actions:
      - vim_make_dirs
      - vim_download_plug
      - vim_install_plugins

profiles:

  darwin:
    dotfiles:
      - ALL
  nimrodel:
    include:
      - darwin
  soft5.vub.ac.be:
    include:
      - nimrodel

  linux:
    dotfiles:
      - tmuxconf
      - ssh_config
      - gitconfig
      - zsh
      - bashrc
      - bash_profile
      - vim
  mirkwood:
    include:
      - linux
  gondolin:
    include:
      - linux
  serenity:
    include:
      - linux
  isabelle:
    include:
      - linux
