config:
  dotpath: ./
  backup: false
  banner: false
  link_dotfile_default: link
  import_variables:
    - hosts.yaml:optional
    - uservariables.yaml:optional

dotfiles:
  # Core set -----------------------------------------------------------------
  bashrc:
    src: bash/bashrc
    dst: ~/.bashrc
  bash_profile:
    src: bash/bashrc
    dst: ~/.bash_profile

  gitconfig:
    src: git/config
    dst: ~/.config/git/config
  gitignore:
    src: git/ignore
    dst: ~/.config/git/ignore

  tmuxconf:
    src: tmux/tmux
    dst: ~/.config/tmux/tmux.conf

  vim:
    src: vim
    dst: ~/.vim/
    link: link_children
    actions:
      - vim_make_dirs

  zshrc:
    src: zsh/zshrc
    dst: ~/.zshrc
  # ---------------------------------------------------------------------------

  emacs:
    src: emacs
    dst: ~/.config/emacs/
    link: link_children

  latexmkrc:
    src: tex/latexmkrc
    dst: ~/.config/latexmk/latexmkrc

  ssh_config:
    src: ssh/config
    dst: ~/.ssh/config

  tex:
    src: tex/packages/
    dst: ~/.config/tex

  # Mail set ------------------------------------------------------------------
  neomutt:
    src: neomutt
    dst: ~/.config/neomutt
    link: link_children
    actions:
      - neomutt_create_cache_dir
  neomutt_accounts:
    src: _accounts/neomutt
    dst: ~/.config/neomutt
    link: link_children

  mailcap:
    src: mailcap/mailcap
    dst: ~/.mailcap

  mbsync:
    src: _accounts/mbsync/mbsyncrc
    dst: ~/.mbsyncrc
    actions:
      - mbsync_create_maildirs

  msmtp:
    src: _accounts/msmtp/config
    dst: ~/.config/msmtp/config

  netrc:
    src: _accounts/netrc
    dst: ~/.netrc
  # ---------------------------------------------------------------------------


actions:
  vim_make_dirs: mkdir -p ~/.vim/backup ~/.vim/swap ~/.vim/undo ~/.vim/sessions
  mbsync_create_maildirs: ~/.dotfiles/_accounts/mbsync/create_dirs.sh
  neomutt_create_cache_dir: mkdir -p ~/.tmp/neomutt/cache/header/

variables:
  mail: false
  path: false
  userctl: false
  paste_cmd: false
  ssh_client: false
  editor: vim
  visual: vim

uservariables:
  email: "email"

profiles:
  # Core set of config to include everywhere.
  # Use -p core when only this set is needed.
  core:
    dotfiles:
      - bashrc
      - bash_profile
      - gitconfig
      - gitignore
      - tmuxconf
      - vim
      - zshrc

  # Set for machines that will ssh to other machines.
  ssh-client:
    variables:
      ssh_client: true
    dotfiles:
      - ssh_config

  # Set for mail-related utilities
  # Needs to be upated
  mail:
    dotfiles:
      - neomutt
      - neomutt_accounts
      - mailcap
      - mbsync
      - msmtp
      - netrc
    variables:
      mail: true

  trusted:
    dotfiles:
      - ssh_config
    variables:
      trusted: true

  # Hostname-based profiles
  silverlode:
    variables:
      paste-cmd: pbpaste
    include:
      - core
      - mail
      - ssh-client
    dotfiles:
      - emacs
      - latexmkrc
      - tex

  sirion:
    variables:
      userctl: true
      paste-cmd: wl-paste
    include:
      - core
      - ssh-client
    dotfiles:
      - emacs
