[[profile]]
name = "laptop"
exec = [
  "xbacklight -set 10",
  "powerprofilesctl set balanced",
  "~/.config/swayidle/select.sh laptop"
]

  [[profile.output]]
  search = ["n=eDP-1"]
  position = "0,0"
  enable = true

[[profile]]
name = "projector"
exec = ["~/.config/swayidle/select.sh projector"]

  [[profile.output]]
  search = ["n=eDP-1"]
  position = "0,0"
  enable = true

  [[profile.output]]
  search = ["n%DP-"]
  position = "2560,295"
  enable = true
  exec = ["swaymsg workspace projector, move workspace to $SHIKANE_OUTPUT_NAME"]

[[profile]]
name = "desk@home"
exec = [
  "~/.config/swayidle/select.sh docked",
  "powerprofilesctl set performance"
]

  [[profile.output]]
  search = ["m=MSI MAG323UPF", "v=Microstep"]
  position = "0,0"
  enable = true
  exec = ["swaymsg workspace web, move workspace to $SHIKANE_OUTPUT_NAME"]

  [[profile.output]]
  search = ["n=eDP-1"]
  position = "3840,345"
  enable = true

[[profile]]
name = "desk+projector@home"
exec = [
  "~/.config/swayidle/select.sh projector",
  "powerprofilesctl set performance"
]

  [[profile.output]]
  search = ["m=MSI MAG323UPF", "v=Microstep"]
  position = "0,0"
  enable = true
  exec = ["swaymsg workspace web, move workspace to $SHIKANE_OUTPUT_NAME"]

  [[profile.output]]
  search = ["m=TX-SR444", "s=", "v=ONKYO Corporation"]
  position = "781,2160"
  enable = true
  exec = ["swaymsg workspace projector, move workspace to $SHIKANE_OUTPUT_NAME"]

  [[profile.output]]
  search = ["n=eDP-1"]
  position = "3840,345"
  enable = true

