{%@@ if os == "linux" @@%}
{#@@ I don't use bash that often, source the distro defined skel file @@#}
source /etc/skel/.bashrc
{%@@ endif @@%}

export EDITOR={{@@ editor @@}}
export VISUAL={{@@ visual @@}}
{%@@ if path @@%}export PATH={{@@ path @@}}{%@@ endif @@%}
