{%@@ if os == "linux" @@%}
{#@@ I don't use bash that often, source the distro defined skel file @@#}
source /etc/skel/.bashrc
{%@@ endif @@%}

export EDITOR={{@@ editor @@}}
export VISUAL={{@@ visual @@}}
{%@@ if path @@%}
export PATH={{@@ path @@}}:$PATH
{%@@ endif @@%}
{%@@ if manpath @@%}
export MANPATH={{@@ manpath @@}}:$MANPATH
{%@@ endif @@%}
{%@@ if infopath @@%}
export INFOPATH={{@@ infopath @@}}:$INFOPATH
{%@@ endif @@%}
